language: generic 
sudo: reuired
services:
  - docker

before_install:
  - docker build -t pranav/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pranav/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-732704833026"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
